### ISSUE TITLE
Duplicate APs

### ISSUE THREAD

**Issue by bobOnGitHub** [digsrc/wpa_supplicant#3]
When I use a hidden SSID on my wifi router I get 2 APs for the same device.

```
[root@localhost sysctl.d]# nmcli dev wifi list --rescan yes
IN-USE  BSSID              SSID              MODE   CHAN  RATE        SIGNAL  BARS  SECURITY         
*       14:49:BC:09:F7:68  BPWLAN2           Infra  6     130 Mbit/s  100     ▂▄▆█  WPA2             
*       14:49:BC:09:F7:68  BPWLAN2           Infra  6     130 Mbit/s  87      ▂▄▆█  WPA2       

[root@localhost sysctl.d]# nmcli --fields ACTIVE,NAME,SSID,DBUS-PATH dev wifi list
ACTIVE  NAME    SSID              DBUS-PATH                                      
yes     AP[1]   BPWLAN2           /org/freedesktop/NetworkManager/AccessPoint/47 
yes     AP[2]   BPWLAN2           /org/freedesktop/NetworkManager/AccessPoint/60 
```

With a visibe SSID it doesn't happen.

Do you know why this is  ?

**EDIT:**

Apparently this was not the place to post this question. I contacted the wpa_supplicant author (details on contacting the project are [here](https://w1.fi/wpa_supplicant/)) and he very kindly responded with the following explanation (which I leave here for future googlers) :

wpa_supplicant supports APs that support multiple SSIDs using the same
BSSID. The hidden SSID case is special in a way that misuses the
standard and provide a zero length SSID in Beacon frames and there is no
way for the receiver to know whether that zero length SSID means that
only a single SSID is actually hidden or whether the AP supports
multiple SSIDs. wpa_supplicant will maintain two entries for such cases,
i.e., one for the empty SSID and one for the SSID that was learned
through an active scan based on the local configuration. It is up to
upper layers (like NetworkManager) if they want to filter out the
zero-length SSID based on an assumption that the AP is only supporting a
single SSID. Should the AP actually support multiple SSIDs,
wpa_supplicant would maintain a separate entry for each different SSID
in addition to the zero-length one.

**Comment by jonjonarnearne** [comment]
Hi @bobOnGitHub.
I don't think this is the official wpa_supplicant repository.

This is the hompage of official project:
https://w1.fi/wpa_supplicant/
